// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func NewGameForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/players\" id=\"new-game-form\" hx-target=\"main\" hx-swap=\"innerHTML\" class=\"content-container gap-4\"><h2 class=\"form-heading\">Add players</h2><div id=\"new-game-form__inputs-container\" class=\"flex w-2/3 flex-col items-center justify-center gap-3\"><input class=\"input-txt\" type=\"text\" name=\"player0-name\" id=\"player0-name\" placeholder=\"Player1 Name\" required> <input class=\"input-txt\" type=\"text\" name=\"player1-name\" id=\"player1-name\" placeholder=\"Player2 Name\" required></div><div class=\"flex justify-center\"><button class=\"btn transition duration-300 hover:bg-blue-800 focus:bg-blue-800 active:bg-blue-800\" type=\"submit\" id=\"new-game-form__button\">Start Game</button></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
